/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaapplication1;

import java.awt.Image;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapplication1.MYSQLConn;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 80924
 */
public class OrderRemind extends javax.swing.JFrame {

    /**
     * Creates new form OrderRemind
     */
     private static String url="jdbc:mysql://localhost:3306/bookstore?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";
     private static String user="root";
    private static String password="ysz319";
    private static Connection con;
    private DefaultTableModel dtm=new DefaultTableModel();
    private Vector<String> title=new Vector<String>();
    private Vector<Vector<String>> data=new Vector<Vector<String>>();
    private String cid;
    public OrderRemind(){
        initComponents();
    }
    public OrderRemind(String id) {
        initComponents();
        this.setTitle("订单");
        this.setLocation(600, 200);
         ImageIcon icon3=new ImageIcon("书2.png");  
        icon3.setImage(icon3.getImage().getScaledInstance(16,16,Image.SCALE_DEFAULT));
        this.setIconImage(icon3.getImage());
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        dtm=(DefaultTableModel)jTable1.getModel();
        cid=id;
        data=MYSQLConn.selectData(cid);
        //System.out.println(data);
        for(int i=0;i<data.size();i++)
        {
            Vector<String> line=new Vector<String>();
            for(int j=0;j<7;j++)
            {
                line.add(data.get(i).get(j));
            }
            System.out.println(data.get(i).get(7));
            if(data.get(i).get(7).equals("1"))
            {
                line.add("未出货");
            }
            else 
            {
                line.add("已出货");
            }
            dtm.addRow(line);
        }
        jTable1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("确认出货");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "买家ID", "商品ID", "数量", "金额", "电话", "地址", "备注", "是否已经出货"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        jButton2.setText("返回");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(MYSQLConn.upData(cid))
        {
            JOptionPane.showMessageDialog(null, "出货成功","系统提示",JOptionPane.INFORMATION_MESSAGE);
            for(int i=0;i<data.size();i++)
            {
                MYSQLConn.updateBook(data.get(i).get(1));
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "出货失败或是没有未出货订单","系统提示",JOptionPane.INFORMATION_MESSAGE);
        }
        data=MYSQLConn.selectData(cid);
        dtm.setRowCount(0);
            for(int i=0;i<data.size();i++)
            {
                Vector<String> line=new Vector<String>();
                for(int j=0;j<7;j++)
                {
                    line.add(data.get(i).get(j));
                }
                if(data.get(i).get(7).equals("1"))
                {
                    line.add("未出货");
                }
                else 
                {
                    line.add("已出货");
                }
                dtm.addRow(line);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String cty="";
        hall h=new hall();
        Sellers_hall S=new Sellers_hall();
         try {
                 Class.forName("com.mysql.cj.jdbc.Driver");
                con=DriverManager.getConnection(url,user,password);
               String sql="select ctype from consumer where consumer_id like '"+cid+"'";//查询语句
               Statement stmt=con.createStatement();
              ResultSet rs=stmt.executeQuery(sql);//将查询结果给rs
             System.out.println(cid);
              while(rs.next()){
                 cty=rs.getString("ctype");
              }
              System.out.println(cty);
               if(cty.equals("1")) h.M_hall(cid);
               else S.S_hall(cid);
                   this.dispose();
                    // System.out.println("被点击 fileMenu");
                } catch (Exception ex) {
                    Logger.getLogger(hall.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderRemind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderRemind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderRemind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderRemind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderRemind("20200114101").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
