/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaapplication1;

import java.awt.Image;
import java.awt.Point;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapplication1.MYSQLConn;
import javaapplication1.Order;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 80924
 */
public class shopping_cart extends javax.swing.JFrame {
     private static String ID;
     private static String url="jdbc:mysql://localhost:3306/bookstore?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC";
     private static String user="root";
    private static String password="ysz319";
    private static Connection con;
    
    /**
     * Creates new form shopping_cart
     */
    int row;
    private DefaultTableModel model=new DefaultTableModel();
    private Vector<Vector<String>> data=new Vector<Vector<String>>();
    public shopping_cart(String id) {
        this.ID=id;
        initComponents();
        this.setTitle("购物车");
        this.setLocation(300, 300);
         ImageIcon icon3=new ImageIcon("书2.png");  
        icon3.setImage(icon3.getImage().getScaledInstance(16,16,Image.SCALE_DEFAULT));
        this.setIconImage(icon3.getImage());
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        model=(DefaultTableModel)jTable2.getModel();
        data=MYSQLConn.selectOrderCard(id);
        //System.out.println(data);
        for(int i=0;i<data.size();i++)
        {
            Vector<String> line=new Vector<String>();
            for(int j=0;j<6;j++)
            {
                line.add(data.get(i).get(j));
            }
            model.addRow(line);
        }
    }
    class OrderThread extends Thread{
        Vector<String> bid=new Vector<String>();
        Vector<Double> num=new Vector<Double>();
        String id=new String();
        public OrderThread(Vector<String> bid,Vector<Double> num,String id)
        {
            this.bid=bid;
            this.num=num;
            this.id=id;
        }
    @Override
    public void run() {
        Order ord=new Order(bid,num,ID);//按确认下单后，打开新窗口，并将要购买的书籍编号和数量，已经顾客的id做为参数传输
        ord.setVisible(true);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        jScrollPane4.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("确定下单");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("删除此商品");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "订单编号", "书籍编号", "书名", "店家", "单价", "数量"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jScrollPane1.setViewportView(jScrollPane2);

        jButton3.setText("返回");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(86, 86, 86)
                        .addComponent(jButton3)))
                .addGap(116, 116, 116))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Vector<String> bid=new Vector<String>();
        Vector<String> snum=new Vector<String>();
        Vector<Double> num=new Vector<Double>();
        for(int i=0;i<data.size();i++)
        {
            bid.add(data.get(i).get(1));
            snum.add(jTable2.getValueAt(i,5).toString());
            num.add(Double.valueOf(snum.get(i)));         
        }
         Order ord=new Order(bid,num,ID);
         ord.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
        //System.out.println(row);
        String id=data.get(row).get(0);
        //System.out.println(id);
        boolean flag=MYSQLConn.DeleteOrderCard(id);
        if(flag)
        {
            JOptionPane.showMessageDialog(null, "删除成功","系统提示",JOptionPane.INFORMATION_MESSAGE);
            data=MYSQLConn.selectOrderCard(ID);
            model.setRowCount(0);
            for(int i=0;i<data.size();i++)
            {
                Vector<String> line=new Vector<String>();
                for(int j=0;j<6;j++)
                {
                    line.add(data.get(i).get(j));
                }
                model.addRow(line);
            }
        }
        else
        {   
            JOptionPane.showMessageDialog(null, "删除失败\n请重新检查","系统提示",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
         row= jTable2.getSelectedRow();
         //System.out.println(row);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       
       String cty="";
        hall h=new hall();
        Sellers_hall S=new Sellers_hall();
         try {
                 Class.forName("com.mysql.cj.jdbc.Driver");
                con=DriverManager.getConnection(url,user,password);
               String sql="select ctype from consumer where consumer_id like '"+ID+"'";//查询语句
               Statement stmt=con.createStatement();
              ResultSet rs=stmt.executeQuery(sql);//将查询结果给rs
             
              while(rs.next()){
                 cty=rs.getString("ctype");
              }
               if(cty.equals("1")) h.M_hall(ID);
               else S.S_hall(ID);
                   this.dispose();
                    // System.out.println("被点击 fileMenu");
                } catch (Exception ex) {
                    Logger.getLogger(hall.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_jButton3ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shopping_cart("1111111").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
